### ISSUE TITLE
request for color name / title / label

### ISSUE THREAD

**Issue by dynegara** [bgaze/bootstrap-color-picker#2]
first, this amazing color picker, l love it.

can you enhance the method bcp(color) so the return include the color name / label / title ?

regards
dyn

**Comment by bgaze** [comment]
Hi @dynegara 

First thanks for your feedback, I'm glad that this package helps you :-)

I've updated it to do that, please see release [1.1.2](https://github.com/bgaze/bootstrap-color-palette/releases/tag/1.1.2).
